import { preprocessRgbaForModel } from '@/features/scan/lib/ml/model-input';

import fixture from './preprocess-parity.fixture.json';

/**
 * Parity with the training preprocessing. The fixture was generated by running the real
 * ml-training/common/opencv_preprocess.py (white_balance_gray_world -> normalize_contrast ->
 * cv2.resize INTER_AREA) on three dataset images; the app must produce the same pixels from the
 * same input, otherwise the model sees data it was never trained on.
 */
type ParityCase = { name: string; size: number; input: string; expected: string };

function rgbToRgba(rgb: Uint8Array): Uint8Array {
  const rgba = new Uint8Array((rgb.length / 3) * 4);
  for (let p = 0, i = 0, o = 0; p < rgb.length / 3; p++, i += 3, o += 4) {
    rgba[o] = rgb[i];
    rgba[o + 1] = rgb[i + 1];
    rgba[o + 2] = rgb[i + 2];
    rgba[o + 3] = 255;
  }
  return rgba;
}

describe('app preprocessing matches the training pipeline', () => {
  for (const testCase of (fixture as { cases: ParityCase[] }).cases) {
    it(`${testCase.name}: white balance -> CLAHE -> 2:1 area downscale`, () => {
      const input = new Uint8Array(Buffer.from(testCase.input, 'base64'));
      const expected = new Uint8Array(Buffer.from(testCase.expected, 'base64'));
      const tensor = preprocessRgbaForModel(rgbToRgba(input), testCase.size, testCase.size);

      expect(tensor.length).toBe(expected.length);

      let sumAbs = 0;
      let maxAbs = 0;
      for (let i = 0; i < tensor.length; i++) {
        const diff = Math.abs(tensor[i] - expected[i]);
        sumAbs += diff;
        maxAbs = Math.max(maxAbs, diff);
      }

      // Measured: mean 0.6-2.6, max 5-10 (of 255). The remainder is OpenCV's fixed-point 8-bit LAB
      // conversion vs this float port, amplified by CLAHE on dark, flat images such as Leather.
      // The previous CLAHE port (edge-tile blending + rounded clip limit) measured max 18 here, so
      // these bounds fail if either bug returns.
      expect(sumAbs / tensor.length).toBeLessThan(3);
      expect(maxAbs).toBeLessThan(12);
    });
  }
});
